{
 "title": "IoT Sensor Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IoT Sensor Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sample_sensor_metric_humidity", "legendFormat": "{{sensor_name}}" }
   ]
  },
  {
   "title": "IoT Sensor AVG Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sample_sensor_metric_temperature",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "IoT Sensor  Luminosity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sample_sensor_metric_luminosity",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "IoT Sensor Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sample_sensor_metric_pressure", "legendFormat": "{{sensor_name}}" }
   ]
  },
  {
   "title": "IoT Sensor Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Grados" }
   ],
   "targets": [
    {
     "expr": "sample_sensor_metric_temperature",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  }
 ]
}